import { z } from "zod";
import type { AdBoard, AdSlot } from "@/lib/ad-board";
import type { SeedanceAudioCapability } from "@/lib/seedance-audio";

export const layerOwnerSchema = z.enum(["native", "generated", "post_mix", "none"]);
export const audioLayerSchema = z.enum(["dialogue", "ambience", "sfx"]);

export const audioOverrideSchema = z.object({
  owner: layerOwnerSchema,
  reason: z.string().trim().min(3),
  by: z.string().trim().min(1),
  at: z.string().datetime(),
}).strict();

export const audioPlanSchema = z.object({
  dialogue: z.object({
    owner: layerOwnerSchema,
    source: z.literal("locked_tts"),
    tts_asset_id: z.string().trim().min(1).nullable().optional().default(null),
    framing_constraint: z.literal("off_face").nullable().optional().default(null),
  }).strict(),
  ambience: z.object({
    owner: layerOwnerSchema,
    description: z.string().trim(),
  }).strict(),
  sfx: z.object({
    owner: layerOwnerSchema,
    events: z.array(z.object({
      desc: z.string().trim().min(1),
      at_ms: z.number().int().nonnegative().optional(),
    }).strict()).max(12),
  }).strict(),
  music: z.object({
    owner: z.literal("post_mix"),
  }).strict(),
  overrides: z.partialRecord(audioLayerSchema, audioOverrideSchema).default({}),
}).strict();

export type LayerOwner = z.infer<typeof layerOwnerSchema>;
export type AudioLayer = z.infer<typeof audioLayerSchema>;
export type AudioPlan = z.infer<typeof audioPlanSchema>;

export type AudioPlanCard = {
  delivery_at_rest?: string;
  delivery_under_pressure?: string;
  signature_sfx?: string[];
};

export type AudioPlanIssue = {
  level: "warning" | "failure";
  rule: "L-audio-1" | "L-audio-2" | "L-audio-3" | "L-audio-4" | "L-audio-5" | "L-audio-6";
  message: string;
};

export const DEFAULT_AUDIO_PLAN: AudioPlan = {
  dialogue: {
    owner: "none",
    source: "locked_tts",
    tts_asset_id: null,
    framing_constraint: null,
  },
  ambience: { owner: "generated", description: "" },
  sfx: { owner: "generated", events: [] },
  music: { owner: "post_mix" },
  overrides: {},
};

const MUSIC_TOKENS = /\b(?:music|musical|score|soundtrack|orchestral|melody|leitmotif|theme|underscore)\b/i;
const OFF_FACE_CAMERA = /\b(?:over[- ]shoulder|hands?|profile|listener|off[- ]face|rear|back of (?:the )?head)\b/i;

function physicalAmbience(slot: Pick<AdSlot, "set" | "weather" | "location">) {
  const values = [
    slot.location ? `location: ${slot.location}` : "",
    slot.set ? `set: ${slot.set}` : "",
    slot.weather && !/^(?:none|clear|interior)$/i.test(slot.weather) ? `weather: ${slot.weather}` : "",
  ].filter(Boolean);
  return values.length ? `Physical room tone from ${values.join("; ")}` : "restrained physical room tone from the visible location";
}

function initialEvents(slot: AdSlot) {
  if (slot.audio_plan.sfx.events.length) return slot.audio_plan.sfx.events;
  const description = slot.audio.sfx.trim();
  return description ? [{ desc: description }] : [];
}

function matchesSignature(description: string, card: AudioPlanCard) {
  const normalized = description.toLowerCase();
  return (card.signature_sfx ?? []).some((event) => {
    const words = event.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter((word) => word.length >= 4);
    return words.some((word) => normalized.includes(word));
  });
}

function applyOverride(
  layer: AudioLayer,
  resolved: LayerOwner,
  plan: AudioPlan,
  capability: SeedanceAudioCapability,
) {
  const override = plan.overrides[layer];
  if (!override) return resolved;
  if (layer === "dialogue" && override.owner === "generated") {
    throw new Error("Actor dialogue may never be generated by the video or sound model.");
  }
  if (override.owner === "native" && !capability.native_audio_output) {
    throw new Error(`${layer} cannot be native because this video model has no native audio output.`);
  }
  if (layer === "dialogue" && override.owner === "native" && !capability.audio_reference_input) {
    throw new Error("Native dialogue requires a model that accepts the locked TTS audio reference.");
  }
  return override.owner;
}

/**
 * Resolves who owns each layer before any provider request is built.
 *
 * Dialogue is special: `native` means Seedance performs the already-rendered,
 * locked ElevenLabs recording. It never authorizes Seedance to invent speech.
 */
export function resolveAudioPlan(
  slot: AdSlot,
  capability: SeedanceAudioCapability,
  card: AudioPlanCard = {},
  audioMode: AdBoard["audio_mode"] = "resolved",
): AudioPlan {
  const line = slot.vo_line?.trim() ?? "";
  const events = initialEvents(slot);
  const legacy = audioMode === "legacy_stems";
  const canReferenceDialogue = !legacy
    && capability.audio_reference_input
    && capability.native_audio_output
    && Boolean(slot.dialogue_asset_id)
    && Boolean(slot.dialogue_url)
    && slot.motion.mode !== "ff_lf";

  if (
    canReferenceDialogue
    && slot.dialogue_duration_ms
    && slot.dialogue_duration_ms > Math.min(capability.max_audio_ref_ms, slot.duration_ms - 500)
  ) {
    throw new Error(
      `Locked TTS for ${slot.id} is ${slot.dialogue_duration_ms}ms; native dialogue must fit within the slot minus 500ms and the ${capability.max_audio_ref_ms}ms provider ceiling.`,
    );
  }

  let dialogueOwner: LayerOwner = line ? (canReferenceDialogue ? "native" : "post_mix") : "none";
  let ambienceOwner: LayerOwner = legacy
    ? "generated"
    : capability.native_audio_output ? "native" : "generated";
  const needsAtomicSfx = events.some((event) => event.at_ms != null || matchesSignature(event.desc, card));
  let sfxOwner: LayerOwner = events.length
    ? legacy || !capability.native_audio_output || needsAtomicSfx ? "generated" : "native"
    : "none";

  dialogueOwner = applyOverride("dialogue", dialogueOwner, slot.audio_plan, capability);
  ambienceOwner = applyOverride("ambience", ambienceOwner, slot.audio_plan, capability);
  sfxOwner = applyOverride("sfx", sfxOwner, slot.audio_plan, capability);

  if (dialogueOwner === "native" && (!slot.dialogue_asset_id || !slot.dialogue_url)) {
    throw new Error("Native dialogue requires a persisted locked-TTS asset and URL.");
  }
  if (dialogueOwner === "native" && slot.motion.mode === "ff_lf") {
    throw new Error("Native dialogue cannot be combined with strict first/last-frame generation; keep dialogue post-mix for this slot.");
  }

  return audioPlanSchema.parse({
    dialogue: {
      owner: dialogueOwner,
      source: "locked_tts",
      tts_asset_id: slot.dialogue_asset_id,
      framing_constraint: line && dialogueOwner !== "native" ? "off_face" : null,
    },
    ambience: {
      owner: ambienceOwner,
      description: physicalAmbience(slot),
    },
    sfx: { owner: sfxOwner, events },
    music: { owner: "post_mix" },
    overrides: slot.audio_plan.overrides,
  });
}

export function audioPlanUsesNative(plan: AudioPlan) {
  return plan.dialogue.owner === "native"
    || plan.ambience.owner === "native"
    || plan.sfx.owner === "native";
}

export function planSlotAudioMix(slot: AdSlot, nativeAudioPresent: boolean) {
  const nativeAudioUsed = nativeAudioPresent && audioPlanUsesNative(slot.audio_plan);
  const dialogueFallbackToPostMix = slot.audio_plan.dialogue.owner === "native" && !nativeAudioUsed;
  return {
    nativeAudioUsed,
    dialogueFallbackToPostMix,
    includeDialogue: Boolean(slot.vo_line && slot.dialogue_url) && (
      slot.audio_plan.dialogue.owner === "post_mix" || dialogueFallbackToPostMix
    ),
    includeAmbience: slot.audio_plan.ambience.owner === "generated",
    includeSfx: ["generated", "post_mix"].includes(slot.audio_plan.sfx.owner),
    dialogueOffsetMs: 500,
    musicDuckDb: slot.vo_line ? (slot.vo_kind === "dialogue" ? -20 : -15) : 0,
  };
}

export function buildAudioSceneBlock(input: {
  plan: AudioPlan;
  durationMs: number;
  delivery?: string;
}) {
  const parts = ["[AUDIO SCENE]"];
  const endMs = Math.max(500, input.durationMs - 500);
  if (input.plan.dialogue.owner === "native") {
    parts.push(
      `[DIALOGUE] actor speaks the supplied audio reference at 500-${endMs}ms, lip-sync to provided audio.${input.delivery ? ` Delivery: ${input.delivery}.` : ""}`,
    );
  }
  if (input.plan.ambience.owner === "native" && input.plan.ambience.description) {
    parts.push(`[AMBIENCE] ${input.plan.ambience.description}`);
  }
  if (input.plan.sfx.owner === "native") {
    for (const event of input.plan.sfx.events.slice(0, 2)) {
      parts.push(`[SFX] ${event.desc}${event.at_ms != null ? ` at ${event.at_ms}ms` : ""}; tied to the visible action.`);
    }
  }
  const negative = input.plan.dialogue.owner === "native"
    ? "no music, no invented voices, no narration"
    : "no music, no speech, no dialogue, no vocal sounds";
  parts.push(`[AUDIO NEGATIVE] ${negative}`);
  return parts.join("\n");
}

export function lintAudioPlan(input: {
  slot: Pick<AdSlot, "camera" | "dialogue_asset_id" | "vo_line">;
  plan: AudioPlan;
  videoPrompt?: string;
  audioReferenceAttached?: boolean;
}): AudioPlanIssue[] {
  const issues: AudioPlanIssue[] = [];
  if (input.plan.music.owner !== "post_mix") {
    issues.push({ level: "failure", rule: "L-audio-1", message: "Music is timeline-scoped and must remain post_mix." });
  }
  if (
    input.plan.dialogue.owner === "native"
    && (!input.plan.dialogue.tts_asset_id || !input.slot.dialogue_asset_id || !input.audioReferenceAttached)
  ) {
    issues.push({ level: "failure", rule: "L-audio-2", message: "Native dialogue requires the persisted locked-TTS asset to be attached as the video audio reference." });
  }
  if (input.plan.dialogue.owner === "generated") {
    issues.push({ level: "failure", rule: "L-audio-3", message: "Actor dialogue may never be generated; it must use locked TTS." });
  }
  if (input.videoPrompt && MUSIC_TOKENS.test(input.videoPrompt.replace(/\[AUDIO NEGATIVE\][^\n]*/gi, ""))) {
    issues.push({ level: "failure", rule: "L-audio-4", message: "Video prompts cannot request music, score, soundtrack, or theme audio." });
  }
  if (input.plan.sfx.owner === "native" && input.plan.sfx.events.length > 2) {
    issues.push({ level: "warning", rule: "L-audio-5", message: "Native SFX is capped at two visible events per slot." });
  }
  if (
    input.slot.vo_line
    && input.plan.dialogue.owner === "post_mix"
    && !OFF_FACE_CAMERA.test(input.slot.camera)
  ) {
    issues.push({ level: "warning", rule: "L-audio-6", message: "Post-mix dialogue should frame over-shoulder, hands, profile, listener, or another off-face angle." });
  }
  return issues;
}

export function resolveBoardAudioPlans(
  board: AdBoard,
  capability: SeedanceAudioCapability,
  card: AudioPlanCard = {},
) {
  return {
    ...board,
    slots: board.slots.map((slot) => ({
      ...slot,
      audio_plan: resolveAudioPlan(slot, capability, card, board.audio_mode),
    })),
  };
}
