import type { DirectorStudyObservation } from "@/lib/director-research";

export type DirectorResearchStudySeed = {
  id: string;
  sourceUrl: string;
  studyTitle: string;
  workTitle: string;
  sceneLocator: string;
  durationSeconds: number;
  periodLabel: string;
  region: string;
  tags: string[];
  observations: DirectorStudyObservation[];
  candidatePrinciples: string[];
  limitations: string;
};

export const DIRECTOR_RESEARCH_STUDY_SEEDS: DirectorResearchStudySeed[] = [
  {
    id: "master-hands-process-montage-180-200",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Master_Hands_full_movie.webm",
    studyTitle: "Material → worker → system → material",
    workTitle: "Master Hands (1936)",
    sceneLocator: "Wikimedia viewing file 03:00–03:20",
    durationSeconds: 20,
    periodLabel: "Flint, Michigan, 1935–1936",
    region: "Flint, Michigan, United States",
    tags: ["public-domain-scene", "editing", "camera", "blocking", "documentary", "production-design", "1930s", "industry"],
    observations: [
      {
        startSecond: 0,
        endSecond: 7.9,
        evidence: "A small molten flow grows into a bright flame against a rigid industrial grating while the frame remains fixed.",
        craft: "Tight high-angle process detail; static geometry makes the changing material legible.",
        transition: "The transformation develops inside one held shot rather than through faster cutting.",
        narrativeJob: "Establish process energy, heat, and material danger before identifying an operator.",
        inference: "Holding on a physical transformation can create momentum while preserving comprehension.",
        confidence: "high",
      },
      {
        startSecond: 7.9,
        endSecond: 12.3,
        evidence: "A hard cut reveals a worker's lower body, stance, hose, and long tool beside the same grating and active flame.",
        craft: "High angle initially withholds the face and emphasizes balance, body, tool, and hazardous floor relation.",
        transition: "The outgoing material force is answered by the person controlling it.",
        narrativeJob: "Convert an abstract industrial force into readable human action and responsibility.",
        inference: "A causal cut can answer 'who or what controls this force?' without repeating the prior image.",
        confidence: "high",
      },
      {
        startSecond: 12.3,
        endSecond: 15,
        evidence: "A bright flare partially obscures and then reveals more of the standing worker operating the long tool.",
        craft: "Medium-to-full-body industrial view uses smoke and exposure change as active foreground material.",
        transition: "The flare masks the precise boundary between views and briefly reduces spatial certainty.",
        narrativeJob: "Increase sensory intensity while retaining the worker-tool action as the anchor.",
        inference: "Motivated light or smoke can bridge a scale change when the continuing action remains identifiable.",
        confidence: "medium",
      },
      {
        startSecond: 15,
        endSecond: 17.4,
        evidence: "A wider view makes the worker small inside a larger field of platforms, machinery, smoke, and hard industrial edges.",
        craft: "Static wide scale reset; human figure supplies proportion within the production system.",
        transition: "Cut from bodily operation to environmental scale.",
        narrativeJob: "Re-establish where the labor sits inside the larger machine process.",
        inference: "After compressed process details, a wide scale reset restores geography and changes the meaning from individual effort to system.",
        confidence: "high",
      },
      {
        startSecond: 17.4,
        endSecond: 20,
        evidence: "The sequence returns to a tight view of flame and the tool or nozzle producing it.",
        craft: "Close process detail removes most surrounding geography but retains the established force and tool relationship.",
        transition: "Wide system view cuts back to elemental material action.",
        narrativeJob: "Land the sequence on the transformed material process after human and system context are understood.",
        inference: "A process montage can cycle detail → operator → system → detail, with each return carrying more context.",
        confidence: "high",
      },
    ],
    candidatePrinciples: [
      "In process montage, alternate material transformation, worker-tool relation, and system-wide scale so energy never outruns comprehension.",
      "A hard cut becomes causal when the incoming shot reveals the human or machine producing the force shown immediately before it.",
      "Let a physical transformation build within a held shot; cut when the audience needs a new causal or spatial fact.",
      "After compressed action details, use a wide scale reset to restore geography and redefine the individual action inside its larger system.",
    ],
    limitations: "Draft analysis of the public-domain Wikimedia 27:20 viewing file, not the differently timed Library of Congress copy. Visual review used a 20-second research extract, a 2 fps contact sheet, and automated change detection. Audio was excluded, so no score or sound claims are made. The flare around 12.3 seconds makes the exact transition boundary uncertain and is marked medium confidence.",
  },
  {
    id: "great-train-robbery-pursuit-showdown-690-780",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Great_Train_Robbery_(1903).webm",
    studyTitle: "Empty route -> pursuit -> concealed threat -> showdown",
    workTitle: "The Great Train Robbery (1903)",
    sceneLocator: "Wikimedia viewing file 11:30-13:00",
    durationSeconds: 90,
    periodLabel: "United States, 1903",
    region: "Wooded exterior, United States",
    tags: ["public-domain-scene", "action", "camera", "blocking", "editing", "geography", "suspense", "1900s"],
    observations: [
      {
        startSecond: 0,
        endSecond: 8,
        evidence: "A fixed wide view holds an empty diagonal forest path before riders enter from deep background.",
        craft: "The path, tree rows, and open foreground create a readable travel axis before speed arrives.",
        transition: "The sequence begins on absence and environmental geometry rather than immediate action.",
        narrativeJob: "Let the audience learn the route and anticipate an arrival.",
        inference: "Holding an empty route briefly can turn geography into suspense when an expected force has not yet entered.",
        confidence: "high",
      },
      {
        startSecond: 8,
        endSecond: 22,
        evidence: "The mounted posse advances from background to foreground in staggered depth, with lead riders crossing closest to camera while others remain visible behind.",
        craft: "Static camera; diagonal approach separates riders by scale and preserves group direction.",
        transition: "Off-screen expectation becomes visible forward movement without a cut.",
        narrativeJob: "Establish pursuit force, number, speed, and direction in one spatially complete image.",
        inference: "A deep approach can communicate scale and acceleration through changing figure size while the camera preserves orientation.",
        confidence: "high",
      },
      {
        startSecond: 22,
        endSecond: 37.5,
        evidence: "Successive riders clear the foreground and exit while trailing riders complete the same path, allowing the frame to empty again.",
        craft: "Entrances and exits provide internal punctuation inside the held wide shot.",
        transition: "The group passes the spectator and transfers momentum toward the next location.",
        narrativeJob: "Complete the pursuit vector rather than cutting away before the last spatial fact lands.",
        inference: "Let the final member clear a route when the audience needs certainty about group direction and destination.",
        confidence: "high",
      },
      {
        startSecond: 37.5,
        endSecond: 48.4,
        evidence: "A hard cut reveals the fugitives clustered low in a separate clearing, handling the stolen goods while horses remain stationed in the background.",
        craft: "Fixed wide tableau layers loot activity in the foreground and escape capability in the background.",
        transition: "The pursuers' exit direction is answered by the fugitives' vulnerable pause.",
        narrativeJob: "Transfer attention from advancing threat to an unaware target and expose the target's current priority.",
        inference: "A pursuit handoff gains tension when the incoming location shows the quarry occupied before the threat arrives.",
        confidence: "high",
      },
      {
        startSecond: 48.4,
        endSecond: 58.8,
        evidence: "The fugitives continue sorting and dividing the goods while the clearing remains visually open around them.",
        craft: "Duration, not camera movement, makes their exposure and delayed awareness legible.",
        transition: "The shot withholds the pursuers and lets the target activity continue past the point of comfort.",
        narrativeJob: "Build a window of vulnerability before the confrontation.",
        inference: "When the threat location is already known, sustained ordinary task behavior can build suspense more clearly than premature cutting.",
        confidence: "medium",
      },
      {
        startSecond: 58.8,
        endSecond: 76,
        evidence: "Gunfire and smoke enter the tableau; standing figures separate, return fire, change levels, and begin to fall while the horses remain a stable background landmark.",
        craft: "Static wide framing lets smoke bursts, body height, and lateral displacement register as distinct state changes.",
        transition: "The concealed pursuit force becomes an active attack inside the established target space.",
        narrativeJob: "Escalate from exposure to combat while retaining who occupies which area.",
        inference: "In a wide action frame, readable state changes such as standing, firing, falling, and retreating can carry intensity without faster coverage.",
        confidence: "high",
      },
      {
        startSecond: 76,
        endSecond: 86.7,
        evidence: "Repeated smoke blooms briefly obscure figures, then reveal fewer active bodies and more fallen bodies in the same clearing.",
        craft: "Occlusion is temporary; the unchanged frame supplies a before-and-after comparison after each burst clears.",
        transition: "Successive volleys reduce the number and options of the fugitives.",
        narrativeJob: "Make attrition measurable and show the confrontation reaching its outcome.",
        inference: "Smoke and impact effects remain legible when the composition gives the audience a stable baseline for counting changed body states.",
        confidence: "high",
      },
      {
        startSecond: 86.7,
        endSecond: 90,
        evidence: "The action settles into an aftermath state with survivors upright around bodies and reduced movement in the clearing.",
        craft: "The held wide shot allows the new balance of control to become readable after the final burst.",
        transition: "Combat energy resolves into a visible control and casualty state.",
        narrativeJob: "Land the action on consequence rather than ending at peak motion.",
        inference: "A short aftermath hold converts spectacle into story information by showing who remains able to act.",
        confidence: "medium",
      },
    ],
    candidatePrinciples: [
      "Before fast movement, hold a route long enough for its axis, depth, and exits to become readable; anticipation then turns geography into suspense.",
      "A static wide action shot can stay information-dense when entrances, exits, scale changes, smoke, and body-state changes continually revise the situation.",
      "Cut from pursuers completing a travel vector to the quarry occupied by a vulnerable task so the edit transfers momentum and creates dramatic irony.",
      "Treat smoke and impact effects as temporary occlusion: preserve stable landmarks so every reveal communicates a measurable change.",
      "After peak action, hold long enough to reveal survivors, casualties, control, and remaining options.",
    ],
    limitations: "Draft visual analysis of the public-domain Wikimedia 13:28 viewing file, whose timing differs from other Library of Congress and restored copies. Review used a 90-second 1 fps contact sheet plus automated scene-change detection; frame-level boundaries are rounded and two uncertain passages are marked medium confidence. The source is silent and this analysis adds no claims about exhibition accompaniment, tinting, or original projection speed.",
  },
  {
    id: "hitch-hiker-car-to-rocks-pressure-900-990",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Hitch-Hiker.webm",
    studyTitle: "Car enclosure -> exposed terrain -> weapon vector -> reaction pressure",
    workTitle: "The Hitch-Hiker (1953)",
    sceneLocator: "Wikimedia viewing file 15:00-16:30",
    durationSeconds: 90,
    periodLabel: "United States and Mexico, early 1950s",
    region: "Rocky desert roadside, Southwestern United States / Baja California screen world",
    tags: ["public-domain-scene", "suspense", "camera", "blocking", "editing", "sound", "dialogue", "performance", "geography", "1950s", "vehicle"],
    observations: [
      {
        startSecond: 0,
        endSecond: 15,
        evidence: "An armed man is isolated in medium-close framing, then the scene cuts to three men compressed beside a car, briefly opens to empty desert, and returns with one man bracketed against the vehicle by the other two.",
        craft: "Threat-bearing close view -> constrained car-side three-shot -> wide environmental release -> tighter enclosure.",
        transition: "The empty-landscape view interrupts the clustered car geometry before the same constrained relation returns.",
        narrativeJob: "Establish immediate force, physical containment, and the absence of nearby help.",
        inference: "Alternating a threatening close image, tight group blocking, and vacant terrain can make confinement and isolation legible at the same time.",
        confidence: "medium",
        audioEvidence: "Sparse outdoor ambience and separated forceful/hesitant speech turns are interrupted by an abrupt gunshot-like event; measured low-level spans occupy much of the interval.",
        soundFunction: "Vocal hierarchy establishes coercion while the sudden impact punctuates the exchange and the low-level gaps prolong its consequence.",
      },
      {
        startSecond: 15,
        endSecond: 30,
        evidence: "A sustained close view isolates an off-axis gaze before returning to a layered car-side composition in which one body and the vehicle obscure access to the central figure.",
        craft: "Held reaction close-up followed by a deeper, partially obstructed group view and a stable triangular enclosure.",
        transition: "The cut returns from facial attention to the spatial fact of who remains attached to and screened by the car.",
        narrativeJob: "Hold on monitored attention, then re-establish the restricted options around the vehicle.",
        inference: "A close reaction gains pressure when the following wider image reveals that the body is still trapped inside the same controlling geometry.",
        confidence: "medium",
        audioEvidence: "Speech delivery reportedly shifts from brief lightness to defensiveness and renewed control over faint ambience and possible movement/rustle; frequent low-level spans isolate the turns.",
        soundFunction: "Tonal contrast briefly complicates the power dynamic before the directive delivery restores dominance.",
      },
      {
        startSecond: 30,
        endSecond: 45,
        evidence: "Two men hold opposite positions beside the car; one edges toward open frame space, an elevated view reduces both figures within rock and vehicle geometry, and a later extended arm creates a directional barrier across the car.",
        craft: "Stable car-side two-shot -> elevated scale reset -> directional gesture in medium framing.",
        transition: "The high view converts a personal confrontation into exposed spatial geography before the closer gesture narrows it again.",
        narrativeJob: "Show that apparent open space does not equal freedom, then reassert control through blocking.",
        inference: "A wide or elevated reset can clarify possible routes while a subsequent arm or weapon vector visibly removes one of those options.",
        confidence: "medium",
        audioEvidence: "Stern and authoritative speech functions remain foregrounded over subdued ambience, separated by movement/rustling and extended low-level intervals.",
        soundFunction: "Withheld background activity keeps attention on directives and makes each movement bridge feel consequential rather than busy.",
      },
      {
        startSecond: 45,
        endSecond: 60,
        evidence: "A man is isolated against enclosing boulders before the scene returns to the car-side pair, preserving the contrast between rugged open terrain and repeated vehicle-bound positions.",
        craft: "Medium-long isolated terrain view held across a posture shift, then a return to the divided two-shot at the sedan.",
        transition: "The edit tests the isolated figure against the landscape and then restores the vehicle as the controlling spatial anchor.",
        narrativeJob: "Extend uncertainty outside the car without releasing the confrontation from its central control point.",
        inference: "A location can feel more dangerous after briefly isolating one figure within it, even when the scene returns to the original blocking.",
        confidence: "medium",
        audioEvidence: "An urgent correction and compliant response are followed by a gunshot-like impact, an apparently relaxed laugh, another firm directive, and a long measured low-level tail.",
        soundFunction: "The impact divides the exchange; the contrasting relaxed reaction may normalize violence for one participant and deepen emotional asymmetry.",
      },
      {
        startSecond: 60,
        endSecond: 75,
        evidence: "A long firearm and a hand-level exchange dominate the car-side two-shot; a wide boulder-field reset exposes difficult routes, then a firearm-centered close view and unequal standing/lower body positions concentrate the threat.",
        craft: "Object-and-gesture two-shot -> wide geography -> weapon close view -> asymmetrical rocky two-shot.",
        transition: "The scene moves from a controlled exchange to environmental scale and back to body-level dominance.",
        narrativeJob: "Convert verbal pressure into readable direction, terrain cost, and unequal physical position.",
        inference: "A weapon or extended arm becomes a useful edit vector when the next views clarify the route it controls and the body made vulnerable by it.",
        confidence: "medium",
        audioEvidence: "Reported warning, challenge, and action-oriented command functions sit over light rustle and subdued ambience, followed by a measured near-silent span from roughly 68 to 75 seconds.",
        soundFunction: "Escalating directive functions compel action, while the extended low-level interval withholds confirmation and prepares the next impact.",
      },
      {
        startSecond: 75,
        endSecond: 90,
        evidence: "A standing figure dominates a lower figure among rocks, a long firearm then points offscreen, the frame compresses two men shoulder-to-shoulder, and alternating close views isolate opposing offscreen eyelines.",
        craft: "Asymmetrical two-shot -> directional weapon line -> compressed depth -> paired reaction close-ups.",
        transition: "The weapon vector creates a question that the close reactions intensify without immediately restoring wide geography.",
        narrativeJob: "Drive the passage to a threat peak and end on monitored reactions rather than spatial release.",
        inference: "When a weapon or gesture establishes a precise offscreen vector, alternating close reactions can delay the answer while keeping the direction intelligible.",
        confidence: "medium",
        audioEvidence: "An urging command, another gunshot-like event, an evaluative speech turn, a brief dramatic score rise, and a final forceful directive sit above otherwise sparse ambience.",
        soundFunction: "The impact and late score change mark a threshold; the final directive preserves dominance instead of allowing the cue to resolve the scene.",
      },
    ],
    candidatePrinciples: [
      "Use vehicle architecture as blocking: doors, rooflines, windows, and body panels can divide access, conceal bodies, and turn a parked car into a control space.",
      "Alternate compressed interpersonal geometry with a wide terrain reset so the audience understands both immediate coercion and the cost of escape.",
      "Let sparse ambience and low-level gaps isolate vocal tactics; reserve abrupt impacts for structural punctuation rather than continuous noise.",
      "Carry a visible weapon, arm, or eyeline vector into the next shot so withheld offscreen space remains directional rather than confusing.",
      "A threatening impact followed by an emotionally relaxed reaction can create asymmetry, but the timing and event identity require direct human verification.",
      "Introduce score late and briefly when a dry speech-and-ambience passage needs a perceptible threshold; do not let it replace physical scene sound.",
    ],
    limitations: "Draft combined image-and-sound analysis of the U.S.-public-domain Wikimedia 70:58 viewing file, timed at 15:00-16:30; clocks may differ in other copies. Visual evidence came from three 10-frame contact sheets sampled once every three seconds, so intervening motion and exact cut frames require playback. Audio evidence came from gpt-audio-1.5 perception, GPT-5.6 Terra synthesis, and FFmpeg signal measurements; no transcript was created or stored, no dialogue words are retained, and model event labels such as gunshot-like or laughter require human listening. The -38 dB silence detector can classify low ambience as silence. All principles remain draft until an administrator reviews the source passage directly.",
  },
];
