import type { DirectorSourceKind } from "@/lib/director-research";

export type DirectorResearchTrack = "film-craft" | "public-domain-scene" | "period-world" | "ai-production";
export type DirectorResearchPriority = "now" | "next" | "later";

export type DirectorResearchCampaignItem = {
  id: string;
  track: DirectorResearchTrack;
  title: string;
  institution: string;
  sourceUrl: string;
  sourceKind: DirectorSourceKind;
  rightsBasis: string;
  accessNotes: string;
  targetTags: string[];
  researchQuestions: string[];
  priority: DirectorResearchPriority;
  periodLabel?: string;
  region?: string;
};

export type DirectorResearchCoverageTarget = {
  id: string;
  label: string;
  track: DirectorResearchTrack;
  targetApprovedStudies: number;
  reason: string;
};

export const DIRECTOR_RESEARCH_CAMPAIGN_VERSION = "2026.07.31-a";

export const DIRECTOR_RESEARCH_COVERAGE_TARGETS: DirectorResearchCoverageTarget[] = [
  { id: "story", label: "Story change", track: "film-craft", targetApprovedStudies: 12, reason: "Objectives, tactics, reversals, choices, and consequences." },
  { id: "camera", label: "Camera and lens", track: "film-craft", targetApprovedStudies: 12, reason: "Position, distance, lens behavior, movement, and motivated reframing." },
  { id: "blocking", label: "Blocking and geography", track: "film-craft", targetApprovedStudies: 10, reason: "Actor movement, spatial relations, eyelines, and readable action." },
  { id: "editing", label: "Editing and rhythm", track: "film-craft", targetApprovedStudies: 10, reason: "Cut cause, consequence, duration, compression, and release." },
  { id: "sound", label: "Sound and music", track: "film-craft", targetApprovedStudies: 10, reason: "Perspective, ambience, bridges, silence, dialogue, and score." },
  { id: "performance", label: "Screen performance", track: "film-craft", targetApprovedStudies: 8, reason: "Physical tactics, stillness, reaction, status, and interaction with space." },
  { id: "production-design", label: "Production design", track: "film-craft", targetApprovedStudies: 8, reason: "Story-bearing space, objects, surface, palette, and practical constraints." },
  { id: "costume", label: "Costume and makeup", track: "film-craft", targetApprovedStudies: 8, reason: "Silhouette, class, occupation, wear, transformation, and continuity." },
  { id: "period", label: "Historical worlds", track: "period-world", targetApprovedStudies: 24, reason: "Time × region × community × role, with explicit anachronism checks." },
  { id: "public-domain-scene", label: "Timed scene studies", track: "public-domain-scene", targetApprovedStudies: 20, reason: "Second-by-second evidence from rights-cleared moving-image works." },
  { id: "ai", label: "AI production controls", track: "ai-production", targetApprovedStudies: 20, reason: "Dated, model-specific capabilities, limits, cost, latency, and continuity tests." },
];

export const DIRECTOR_RESEARCH_CAMPAIGN: DirectorResearchCampaignItem[] = [
  {
    id: "loc-json-api-era-evidence",
    track: "period-world",
    title: "Library of Congress structured era-evidence discovery",
    institution: "Library of Congress",
    sourceUrl: "https://www.loc.gov/apis/json-and-yaml/",
    sourceKind: "institutional",
    rightsBasis: "Official Library of Congress API documentation used to discover item-level dated evidence and rights metadata; each selected item retains its own rights advisory and record URL.",
    accessNotes: "Use search, format, collection, and item endpoints. Filter by date, location, subject, and collection; preserve item ID, created/published date, place, medium, repository, rights advisory, and access date.",
    targetTags: ["period", "production-design", "costume", "location", "transport"],
    researchQuestions: [
      "Which dated, located records support the exact city, community, occupation, and year in the production brief?",
      "Which rights and metadata fields must remain attached when an observation becomes a reusable world constraint?",
    ],
    priority: "now",
  },
  {
    id: "met-collection-api-material-evidence",
    track: "period-world",
    title: "Met Collection API material-world discovery",
    institution: "The Metropolitan Museum of Art",
    sourceUrl: "https://metmuseum.github.io/",
    sourceKind: "institutional",
    rightsBasis: "Official Metropolitan Museum of Art open-access API documentation used to discover object-level date, culture, geography, medium, and rights information.",
    accessNotes: "Query object IDs, then retain object URL, culture, object begin/end dates, geography, classification, medium, dimensions, repository, public-domain status, and access date.",
    targetTags: ["period", "production-design", "costume", "materials", "objects"],
    researchQuestions: [
      "Which objects and construction materials are evidenced for the resolved culture, date range, role, and location?",
      "How should uncertain or elite ceremonial objects be kept out of ordinary daily-life scenes?",
    ],
    priority: "now",
  },
  {
    id: "academy-craft-guides",
    track: "film-craft",
    title: "Academy Teachers Guide Series",
    institution: "Academy of Motion Picture Arts and Sciences",
    sourceUrl: "https://www.oscars.org/education-grants/teachers-guide-series",
    sourceKind: "institutional",
    rightsBasis: "Official Academy educational material used for analytical craft research; no expressive film content is copied.",
    accessNotes: "Index includes guides for editing, art direction, costume, makeup, sound and music, animation, documentary, screenwriting, and visual effects.",
    targetTags: ["editing", "sound", "production-design", "costume", "vfx", "story"],
    researchQuestions: [
      "Which observable choices define each department's narrative contribution?",
      "Which continuity checks should be measurable before a generated shot is approved?",
    ],
    priority: "now",
  },
  {
    id: "academy-sound-and-music-guide",
    track: "film-craft",
    title: "Sound and Music Activities Guide",
    institution: "Academy of Motion Picture Arts and Sciences",
    sourceUrl: "https://www.oscars.org/sites/oscars/files/complete_sound_and_music_activities_guide.pdf",
    sourceKind: "institutional",
    rightsBasis: "Official Academy educational guide analyzed for attributable craft relationships; no film dialogue, score, lyrics, transcript, or expressive scene content is retained.",
    accessNotes: "Extract only abstract sound-image relationships, listening categories, and measurable continuity checks. Do not reproduce guide passages or referenced film content.",
    targetTags: ["sound", "music", "silence", "perspective", "ambience", "continuity"],
    researchQuestions: [
      "How do dialogue, effects, ambience, silence, and music divide narrative work inside a shot or transition?",
      "Which audible perspective, continuity, intelligibility, and emotional-function checks can be measured before approval?",
    ],
    priority: "now",
  },
  {
    id: "asc-camera-movement",
    track: "film-craft",
    title: "Shot Craft: Tools for Camera Movement",
    institution: "American Society of Cinematographers",
    sourceUrl: "https://theasc.com/articles/shot-craft-camera-movement",
    sourceKind: "institutional",
    rightsBasis: "Official ASC craft article analyzed for reusable relationships; quotations and protected scene expression are not stored.",
    accessNotes: "Research movement purpose, physical tool behavior, operator constraints, and motivated transitions.",
    targetTags: ["camera", "blocking", "movement", "geography"],
    researchQuestions: [
      "What story change motivates a dolly, crane, handheld, or stabilized move?",
      "How should actor marks and camera correction interact without making performance mechanical?",
    ],
    priority: "now",
  },
  {
    id: "asc-location-blocking",
    track: "film-craft",
    title: "John Bailey, ASC: Inside the Outsider",
    institution: "American Society of Cinematographers",
    sourceUrl: "https://theasc.com/articles/john-bailey-asc-inside-the-outsider",
    sourceKind: "filmmaker-interview",
    rightsBasis: "Official ASC filmmaker interview analyzed for abstract craft relationships; no film scene is reconstructed.",
    accessNotes: "Focus on how location, actor choreography, camera, and lighting decisions constrain one another.",
    targetTags: ["blocking", "performance", "camera", "production-design"],
    researchQuestions: [
      "How does location determine playable actor behavior before camera placement?",
      "Which camera constraints protect performance rather than forcing it?",
    ],
    priority: "now",
  },
  {
    id: "loc-public-domain-registry",
    track: "public-domain-scene",
    title: "Public Domain Films from the National Film Registry",
    institution: "Library of Congress",
    sourceUrl: "https://www.loc.gov/free-to-use/public-domain-films-from-the-national-film-registry",
    sourceKind: "public-domain",
    rightsBasis: "The Library of Congress identifies this curated selection as public-domain films that are free to use and reuse; item-level rights notes remain mandatory.",
    accessNotes: "Use as the primary timed-analysis pool. Preserve item URL, access date, rights statement, and exact scene locator.",
    targetTags: ["public-domain-scene", "editing", "camera", "sound", "performance", "period"],
    researchQuestions: [
      "Which seconds change information, tactic, geography, rhythm, or attention?",
      "How do silent, documentary, animation, industrial, and narrative forms solve different problems?",
    ],
    priority: "now",
  },
  {
    id: "loc-great-train-robbery",
    track: "public-domain-scene",
    title: "The Great Train Robbery (1903)",
    institution: "Library of Congress",
    sourceUrl: "https://www.loc.gov/item/00694220/",
    sourceKind: "public-domain",
    rightsBasis: "Listed by the Library of Congress in its public-domain National Film Registry collection; verify the item record before any source-file reuse.",
    accessNotes: "Timed study target: spatial continuity, staging in depth, action legibility, and scene-to-scene escalation.",
    targetTags: ["public-domain-scene", "action", "camera", "blocking", "editing", "1900s"],
    researchQuestions: [
      "How is action geography communicated before continuity editing conventions stabilized?",
      "Which tableau changes carry cause and consequence without close coverage?",
    ],
    priority: "now",
    periodLabel: "United States, 1903",
    region: "United States",
  },
  {
    id: "commons-great-train-robbery-viewing-file",
    track: "public-domain-scene",
    title: "The Great Train Robbery full-movie viewing file",
    institution: "Wikimedia Commons / Library of Congress",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Great_Train_Robbery_(1903).webm",
    sourceKind: "public-domain",
    rightsBasis: "The Wikimedia Commons file record identifies the 1903 U.S. film and digital copy as free of known copyright restrictions under the Public Domain Mark; the Library of Congress independently includes the work in its public-domain National Film Registry selection.",
    accessNotes: "Research copy verified 2026-07-30: 13:28 WebM sourced from the Library of Congress. Timed locators use this file's clock; the Library of Congress item record remains the catalog and rights cross-check.",
    targetTags: ["public-domain-scene", "action", "camera", "blocking", "editing", "geography", "1900s"],
    researchQuestions: [
      "How does static tableau staging maintain readable pursuit and combat geography without modern coverage?",
      "Which entrances, exits, depth changes, smoke events, and body-state changes provide new information inside a held shot?",
    ],
    priority: "now",
    periodLabel: "United States, 1903",
    region: "United States",
  },
  {
    id: "loc-master-hands",
    track: "public-domain-scene",
    title: "Master Hands (1936)",
    institution: "Library of Congress",
    sourceUrl: "https://www.loc.gov/item/2022600183/",
    sourceKind: "public-domain",
    rightsBasis: "Included in the Library of Congress public-domain National Film Registry selection; the item record's rights notice must be retained.",
    accessNotes: "Timed study target: industrial montage, machine-human scale, rhythmic cutting, process clarity, and orchestral counterpoint.",
    targetTags: ["public-domain-scene", "editing", "sound", "camera", "documentary", "1930s", "industry"],
    researchQuestions: [
      "How does montage make a complex process legible while sustaining momentum?",
      "How do scale changes and musical phrasing organize attention?",
    ],
    priority: "now",
    periodLabel: "Flint, Michigan, 1935–1936",
    region: "Flint, Michigan, United States",
  },
  {
    id: "commons-master-hands-viewing-file",
    track: "public-domain-scene",
    title: "Master Hands full-movie viewing file",
    institution: "Wikimedia Commons / Prelinger Archives",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Master_Hands_full_movie.webm",
    sourceKind: "public-domain",
    rightsBasis: "The Wikimedia Commons file record identifies the 1936 U.S. work as public domain because its copyright was not renewed; the Library of Congress public-domain registry listing provides a second rights reference.",
    accessNotes: "Research copy verified 2026-07-30: 27:20 WebM, 320×240. Use this file's clock for timed locators and retain the Library of Congress item URL in study limitations.",
    targetTags: ["public-domain-scene", "editing", "camera", "blocking", "documentary", "1930s", "industry"],
    researchQuestions: [
      "How does the montage alternate material transformation, worker-tool relations, and system-wide scale?",
      "Which cuts add a new causal or spatial fact, and which physical transformations build within a held shot?",
    ],
    priority: "now",
    periodLabel: "Flint, Michigan, 1935–1936",
    region: "Flint, Michigan, United States",
  },
  {
    id: "loc-hitch-hiker",
    track: "public-domain-scene",
    title: "The Hitch-Hiker (1953)",
    institution: "Library of Congress",
    sourceUrl: "https://www.loc.gov/item/mbrs00047382/",
    sourceKind: "public-domain",
    rightsBasis: "Listed in the Library of Congress public-domain National Film Registry collection; item-level rights and access notes remain binding.",
    accessNotes: "Timed study target: confined-space suspense, eyelines, off-screen threat, negative space, silence, and pressure escalation.",
    targetTags: ["public-domain-scene", "suspense", "camera", "blocking", "editing", "sound", "1950s"],
    researchQuestions: [
      "How does a confined frame keep geography readable while restricting options?",
      "When do sound, gaze, and withheld reverse angles move attention?",
    ],
    priority: "next",
    periodLabel: "United States and Mexico, early 1950s",
    region: "Southwestern United States and Baja California",
  },
  {
    id: "commons-hitch-hiker-viewing-file",
    track: "public-domain-scene",
    title: "The Hitch-Hiker full-movie viewing file",
    institution: "Wikimedia Commons / Library of Congress",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_Hitch-Hiker.webm",
    sourceKind: "public-domain",
    rightsBasis: "The Wikimedia Commons file record marks this U.S. film public domain in the United States and cites Library of Congress item mbrs00047382 as confirmation. Jurisdiction-specific reuse caveats remain attached to the file record.",
    accessNotes: "Research copy verified 2026-07-30: 70:58 WebM; the timed study uses 15:00-16:30 on this file's clock. Contact-sheet and audio analysis are transient; no frames, soundtrack, transcript, subtitles, or dialogue are stored in the corpus.",
    targetTags: ["public-domain-scene", "suspense", "camera", "blocking", "editing", "sound", "dialogue", "performance", "1950s", "vehicle"],
    researchQuestions: [
      "How does the car partition access, bodies, eyelines, and escape routes before the action moves into open rocks?",
      "How do sparse ambience, separated speech turns, impact sounds, and late score shape pressure without storing dialogue?",
      "Which weapon vectors, gestures, wide resets, and reaction close-ups create causal edit opportunities?",
    ],
    priority: "now",
    periodLabel: "United States and Mexico, early 1950s",
    region: "Southwestern United States and Baja California",
  },
  {
    id: "met-roman-housing",
    track: "period-world",
    title: "Roman Housing",
    institution: "The Metropolitan Museum of Art",
    sourceUrl: "https://www.metmuseum.org/essays/roman-housing",
    sourceKind: "institutional",
    rightsBasis: "Metropolitan Museum scholarly essay used as historical evidence with source attribution; no object image is redistributed.",
    accessNotes: "Distinguish elite domus and villas, urban insulae, rural farms, and worker housing before defining a Roman interior.",
    targetTags: ["period", "production-design", "architecture", "rome", "first-century"],
    researchQuestions: [
      "How do class, work, and geography alter Roman domestic space?",
      "Which materials, circulation patterns, displays, hazards, and light sources are evidenced?",
    ],
    priority: "now",
    periodLabel: "Roman Italy, first century CE",
    region: "Italy within the Roman Empire",
  },
  {
    id: "met-uruk-first-city",
    track: "period-world",
    title: "Uruk: The First City",
    institution: "The Metropolitan Museum of Art",
    sourceUrl: "https://collectionapi.metmuseum.org/public/collection/v1/search?hasImages=true&q=Uruk",
    sourceKind: "institutional",
    rightsBasis: "Metropolitan Museum scholarly essay used as attributed historical evidence; no object images or expressive passages are reproduced.",
    accessNotes: "The official Met Collection API query is expanded into attributable object records. Cross-check the Met scholarly essay 'Uruk: The First City' for chronology. Monumental, administrative, or elite evidence must not be treated as a complete picture of ordinary daily life.",
    targetTags: ["period", "production-design", "architecture", "early-urban", "west-asia", "3000-bce", "uruk"],
    researchQuestions: [
      "Which city scale, irrigation, wall, administrative, craft, and imported-material facts are supported for Uruk near 3000 BCE?",
      "Which claims describe institutions or elite contexts rather than ordinary homes, clothing, work, and street life?",
    ],
    priority: "now",
    periodLabel: "Uruk, southern Mesopotamia, late fourth to early third millennium BCE",
    region: "Uruk, southern Mesopotamia",
  },
  {
    id: "met-art-first-cities",
    track: "period-world",
    title: "Art of the First Cities in the Third Millennium B.C.",
    institution: "The Metropolitan Museum of Art",
    sourceUrl: "https://collectionapi.metmuseum.org/public/collection/v1/search?hasImages=true&q=Mesopotamia%20third%20millennium",
    sourceKind: "institutional",
    rightsBasis: "Official Metropolitan Museum exhibition scholarship used as attributed historical evidence; exhibition images and protected text are not redistributed.",
    accessNotes: "The official Met Collection API query is expanded into attributable object records and interpreted with the Met publication 'Art of the First Cities.' Temple, palace, tomb, luxury, and elite objects remain explicitly exceptional unless ordinary-life evidence independently supports generalization.",
    targetTags: ["period", "production-design", "materials", "trade", "early-urban", "west-asia", "3000-bce"],
    researchQuestions: [
      "How did city-state, regional exchange, and emerging empire change materials, objects, symbols, and built environments during the third millennium BCE?",
      "Which visible production choices can be localized without flattening distinct cities and communities into one ancient-world preset?",
    ],
    priority: "now",
    periodLabel: "Western Asia, third millennium BCE",
    region: "Mesopotamia and connected regions of western Asia",
  },
  {
    id: "met-edo-period",
    track: "period-world",
    title: "Art of the Edo Period (1615–1868)",
    institution: "The Metropolitan Museum of Art",
    sourceUrl: "https://www.metmuseum.org/essays/art-of-the-edo-period-1615-1868",
    sourceKind: "institutional",
    rightsBasis: "Metropolitan Museum scholarly essay and dated object records used as attributed evidence; no protected exhibition text or images are reproduced.",
    accessNotes: "Resolve year, city, class, occupation, occasion, and trade context before selecting objects or costume.",
    targetTags: ["period", "production-design", "costume", "edo", "japan"],
    researchQuestions: [
      "How do samurai, artisan, merchant, court, and performance contexts differ?",
      "Which textiles, ceramics, lacquer, screens, tools, and urban practices belong to a given date and class?",
    ],
    priority: "now",
    periodLabel: "Edo Japan, 1615–1868",
    region: "Edo, Kyoto, or Nagasaki, Japan",
  },
  {
    id: "met-mughal-court",
    track: "period-world",
    title: "The Mughal Court and the Art of Observation",
    institution: "The Metropolitan Museum of Art",
    sourceUrl: "https://www.metmuseum.org/-/media/files/learn/for%20educators/publications%20for%20educators/islamic%20teacher%20resource/unit5.pdf",
    sourceKind: "institutional",
    rightsBasis: "Metropolitan Museum educational publication used for attributed historical research; images and expressive text are not republished.",
    accessNotes: "Start with Jahangir and Shah Jahan court contexts; do not flatten Mughal India into a single pan-Indian visual preset.",
    targetTags: ["period", "production-design", "costume", "mughal", "india", "1600s"],
    researchQuestions: [
      "How do patronage, rank, court ritual, natural observation, and regional exchange shape material choices?",
      "Which precious materials, textiles, architecture, vessels, gardens, and botanical motifs are documented?",
    ],
    priority: "now",
    periodLabel: "Mughal India, 1605–1658",
    region: "Agra, Delhi, Lahore, and the Mughal court",
  },
  {
    id: "smithsonian-open-access-world-evidence",
    track: "period-world",
    title: "Smithsonian Open Access collections and API",
    institution: "Smithsonian Institution",
    sourceUrl: "https://www.si.edu/openaccess/devtools",
    sourceKind: "institutional",
    rightsBasis: "Official Smithsonian Open Access documentation used to discover item-level collection metadata. Only assets explicitly designated CC0 may enter reusable visual evidence; restricted and culturally sensitive records remain metadata-only or excluded.",
    accessNotes: "Verified 2026-07-31. Preserve Smithsonian identifier, title, culture/community, place, date, object type, medium, dimensions, museum, CC0 designation, record URL, access date, and any cultural-sensitivity or third-party warning.",
    targetTags: ["period", "production-design", "costume", "materials", "objects", "technology", "community"],
    researchQuestions: [
      "Which CC0 objects and documentary records fill material-culture gaps outside the existing United States, European, and elite-art baselines?",
      "Which records are culturally sensitive, ceremonial, exceptional, or otherwise unsafe to generalize into everyday production design?",
    ],
    priority: "now",
  },
  {
    id: "europeana-cross-border-world-evidence",
    track: "period-world",
    title: "Europeana Search, Record, IIIF, and rights metadata APIs",
    institution: "Europeana Foundation",
    sourceUrl: "https://pro.europeana.eu/page/apis",
    sourceKind: "institutional",
    rightsBasis: "Official Europeana API documentation used to discover item-level metadata from contributing cultural institutions. Every observation retains the provider, record identifier, item rights statement, media rights statement, and source URL; a searchable record is not presumed reusable.",
    accessNotes: "Verified 2026-07-31. Use Search for discovery and Record/IIIF for item evidence. Preserve dc:date, dc:coverage, dc:type, dc:format, provider/dataProvider, edm:rights, object and shown-at URLs, language, and access date.",
    targetTags: ["period", "production-design", "costume", "location", "transport", "photography", "europe"],
    researchQuestions: [
      "Which dated and located records distinguish regional European streets, domestic life, work, dress, transport, and image language across each era band?",
      "How do conflicting or incomplete rights labels, translated metadata, and provider-specific dating affect confidence and reuse eligibility?",
    ],
    priority: "now",
  },
  {
    id: "dpla-us-community-evidence",
    track: "period-world",
    title: "Digital Public Library of America API and bulk records",
    institution: "Digital Public Library of America",
    sourceUrl: "https://pro.dp.la/developers",
    sourceKind: "institutional",
    rightsBasis: "Official DPLA developer documentation used for federated discovery across United States libraries, archives, and museums. DPLA metadata licensing does not override item-level media rights; the contributing institution and rights field remain attached to every record.",
    accessNotes: "Verified 2026-07-31. Use DPLA for cross-institution discovery by date, place, subject, type, provider, and rights. Follow the item back to the contributing institution before approving visual evidence.",
    targetTags: ["period", "production-design", "costume", "location", "transport", "work", "community", "united-states"],
    researchQuestions: [
      "Which local archives fill city, neighborhood, occupation, class, race, migration, and everyday-life gaps that national collections underrepresent?",
      "Which item-level rights and provenance checks must pass before a discovered record can support a production constraint?",
    ],
    priority: "next",
  },
  {
    id: "loc-look-midcentury-america",
    track: "period-world",
    title: "Look Magazine Photograph Collection",
    institution: "Library of Congress",
    sourceUrl: "https://www.loc.gov/collections/look-magazine/about-this-collection/?fo=json",
    sourceKind: "institutional",
    rightsBasis: "Official Library of Congress collection description used for provenance and dated discovery. A collection record does not clear every photograph; item-level rights and access restrictions remain binding.",
    accessNotes: "Use the 1951-1971 assignment archive, especially the dense 1954-1964 coverage, to locate dated records. Many photographs are not digitized, so retain metadata-only evidence unless an item record exposes a reusable image with adequate rights.",
    targetTags: ["period", "production-design", "costume", "location", "work", "community", "1950s", "1960s", "united-states"],
    researchQuestions: [
      "Which dated assignments document ordinary work, domestic, street, leisure, advertising, and public-life contexts in the 1950s and 1960s?",
      "Which demographic, editorial, digitization, and rights limits prevent a photograph or assignment from becoming a general period rule?",
    ],
    priority: "now",
    periodLabel: "United States, 1951-1971",
    region: "United States",
  },
  {
    id: "openai-sora-video-api",
    track: "ai-production",
    title: "OpenAI Video API",
    institution: "OpenAI",
    sourceUrl: "https://developers.openai.com/api/reference/resources/videos",
    sourceKind: "provider-research",
    rightsBasis: "Official public API documentation used to record dated capability and request-contract facts.",
    accessNotes: "As verified 2026-07-30: create, edit, extend, remix, character, reference-image, lifecycle, duration, and resolution contracts require separate benchmarks.",
    targetTags: ["ai", "video", "reference", "extension", "editing", "sora"],
    researchQuestions: [
      "Which identity and continuity properties survive reference, edit, extension, and remix operations?",
      "How do 4, 8, and 12-second units differ in usable motion, landing quality, latency, and cost?",
    ],
    priority: "now",
  },
  {
    id: "filmbench-v2-film-grade-evaluation",
    track: "ai-production",
    title: "FilmBench v2 film-grade evaluation taxonomy",
    institution: "Beijing Film Academy and collaborators",
    sourceUrl: "https://arxiv.org/abs/2607.24241",
    sourceKind: "provider-research",
    rightsBasis: "The research paper's evaluation taxonomy is used analytically. Chaplin does not ingest, replay, or reverse engineer the benchmark's film clips or protected prompts.",
    accessNotes: "Use the three-axis taxonomy and expert-ranking method as evaluation guidance: instruction following, temporal continuity, and aesthetic quality. Keep all Chaplin examples original and all output reviews tied to generated artifacts.",
    targetTags: ["ai", "evaluation", "continuity", "camera", "performance", "audio", "editing"],
    researchQuestions: [
      "Which film-grade dimensions expose failures that a single visual-quality score hides?",
      "Which hard continuity gates should block promotion even when a candidate's average score improves?",
    ],
    priority: "now",
  },
  {
    id: "google-video-generation",
    track: "ai-production",
    title: "Video generation in the Gemini API",
    institution: "Google AI for Developers",
    sourceUrl: "https://ai.google.dev/gemini-api/docs/video",
    sourceKind: "provider-research",
    rightsBasis: "Official Google API documentation used to record dated model capabilities and limitations.",
    accessNotes: "As verified 2026-07-30: compare Gemini Omni Flash with Veo 3.1 for multi-input reasoning, character consistency, conversational editing, extension, last-frame control, and native audio.",
    targetTags: ["ai", "video", "audio", "reference", "extension", "editing", "veo", "gemini"],
    researchQuestions: [
      "Which workflow should use conversational editing versus a controlled generation pipeline?",
      "How reliable are native audio, final-frame guidance, extension, and character continuity?",
    ],
    priority: "now",
  },
  {
    id: "runway-video-api",
    track: "ai-production",
    title: "Runway API Reference",
    institution: "Runway",
    sourceUrl: "https://docs.dev.runwayml.com/api/",
    sourceKind: "provider-research",
    rightsBasis: "Official Runway API documentation used for dated request-contract and capability research.",
    accessNotes: "Model availability changes quickly. Store observed model identifier, API version, date, input contract, output evidence, cost, latency, and failure modes.",
    targetTags: ["ai", "video", "reference", "camera", "motion", "runway"],
    researchQuestions: [
      "Which model and input path best preserve identity, camera intent, and a readable action landing?",
      "Which capabilities are native versus routed to third-party models through the API?",
    ],
    priority: "next",
  },
  {
    id: "adobe-firefly-video-api",
    track: "ai-production",
    title: "Adobe Firefly Generate Video API usage notes",
    institution: "Adobe",
    sourceUrl: "https://developer.adobe.com/firefly-services/docs/firefly-api/getting-started/usage-notes/",
    sourceKind: "provider-research",
    rightsBasis: "Official Adobe developer documentation used for dated request-contract, aspect-ratio, and limitation research.",
    accessNotes: "Track supported dimensions, storage constraints, commercial workflow assumptions, model/version changes, and provenance behavior.",
    targetTags: ["ai", "video", "commercial", "aspect-ratio", "firefly"],
    researchQuestions: [
      "How do supported aspect ratios and resolutions change composition reliability?",
      "Which production and provenance controls are useful for commercial delivery?",
    ],
    priority: "later",
  },
];

export function campaignTrackLabel(track: DirectorResearchTrack) {
  if (track === "film-craft") return "Film craft";
  if (track === "public-domain-scene") return "Timed public-domain scenes";
  if (track === "period-world") return "Historical worlds";
  return "AI production";
}
